<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/* 
 * Camper Configuration
 *
 * Camper uses a number of variables throughout the system that help customize
 * it for it's users. From details about where the system files are to URL 
 * definitions, static lists of states of districts or default names. Edit this 
 * customize Camper for your needs.
 *
 * Version 1.5 (2014 12 01 1035)
 * Edited by Sean Wittmeyer (sean@zilifone.net)
 * 
 * Use: $localvar = $this->config->item('camper_path')
 */

/* System Starters
 *
 * These are the system variables that allow Camper to be customized per council. Set these variables to
 * make the system your own. 
 *
 * Since 1.0
 */
 
/* Live Set */
$config['camperapp'] = 1;
$config['camper_path'] = '/camper/';
$config['camper_basepath'] = '/domains/dev.camperapp.org/html/camper/';
//$config['camper_basepath'] = '/domains/ssl.longspeakbsa.org/html/camper/';
$config['camper_systemname'] = 'Camper';
$config['camper_mailaddress'] = '2215 23rd Avenue, Greeley, CO 80632';
$config['camper_debug'] = FALSE; 
$config['camper_domain'] = '';
$config['camper_protocol'] = 'https';
$config['camper_theme'] = 'lpc';
$config['camper_fromname'] = 'Camper';
$config['camper_fromemail'] = '';
$config['camper_supportemail'] = '';
$config['camper_supportphone'] = '';
$config['camper_council'] = 'Longs Peak Council';
$config['camper_councilpublicsite'] = 'http://camps.longspeakbsa.org/';
$config['camper_version'] = '1.5 beta 1';
$config['camper_version_num'] = '1.5b1';
$int = intval('9223372036854775807');
if ($int == 9223372036854775807) {
	$config['camper_architecture'] = 64;
	$config['camper_wkhtmltopdf'] = 'amd64';
}
elseif ($int == 2147483647) {
	$config['camper_architecture'] = 32;
	$config['camper_wkhtmltopdf'] = 'i386';
}
else {
  print_r('Camper can\'t determine 32/64bit architecture for this system, contact the system administrator ('.$camper['camper_supportemail'].') for more details. fx camper config 59');
} 

/* Dev Set */
$config['camper_path'] = '/camper/';
$config['camper_debug'] = TRUE; 
$config['camper_domain'] = '';
$config['camper_protocol'] = 'http';
$config['camper_theme'] = 'lpc';
$config['camper_version'] = '1.4.41 dev';
$config['camper_version_num'] = '1.4.41';

/* Payment Variables
 *
 * These are the system variables that allow Camper to be customized per council. Set these variables to
 * make the system your own. 
 *
 * Since 1.0
 */

$config['camper_pay_driver'] = 'paypal_express';

/* Dev Paypal */
$config['camper_pay_paypal'] = array(
	'username'		=> '',	
	'password'		=> '',	
	'signature'		=> '',	
	'test_mode'		=> true,
	'environment'	=> 'sandbox', // 'sandbox or 'live'
	'headerurl'		=> 'https://ssl.longspeakbsa.org/lpc.small.png' // prefer https
);

/* Live Paypal *
$config['camper_pay_paypal'] = array(
	'username'		=> 'cibatt_api1.bsamail.org',	
	'password'		=> 'ZMZVWGUV398PXJHZ',	
	'signature'		=> 'AFcWxV21C7fd0v3bYYYRCpSSRl31A.pkk8OHMLUUYFuM0SaGeJOE2CFM',	
	'test_mode'		=> false,
	'environment'	=> 'live', // 'sandbox or 'live'
	'headerurl'		=> 'https://ssl.longspeakbsa.org/lpc.small.png' // prefer https
);

/* DO NOT EDIT THIS FILE BELOW THIS LINE!
 *
 * Any changes to the lines below will be erased as Camper updates.
 *
 */
 
 
/* Notifications Content and Action Defaults
 *
 * The notifications system is made of four parts: the defaults here, the $this->shared->notify() function, 
 * the notifications view in header, and the action handler. These are the defaults.
 * Each item is a type associated with an array. 
 *
 * 'invitor' => array(
 *		'i' initiate		=> true, // Initiate the notification type UNUSED
 *		'f' function		=> 'accept', // null or string, name of function that handles the accepted function UNUSED
 *		'l' link			=> 'myunit/edit', // null or string, link of page that handles the action
 *		't' text			=> 'You invited {e} to be a contact for {u}. ', // string, your notification text with mustache vars {e}=email, {f}=firstname, etc
 *		'y' yes/confirm		=> 'Approve this change',
 *		'n' no/reject		=> 'Reject this request'
 *		'sy' short yes		=> 'Approve',
 *		's' email subject	=> false or 'Your invite was sent' // false will not send an email
 *		)
 *
 * Since 1.0
 */

$config['camper_notifications'] = array(
	'newregistrationadmin' => array(
		'i' => true, // User registered for an event
		'f' => null, // no function
		'l' => 'event', // link to myunit to handle this
		't' => '{f} {l} of {u} registered for {s} of {u}. ', // message text, first and last names
		'y' => 'View online', // confirm button
		'sy' => 'View', // short confirm button
		'n' => null, // reject/no button
		's' => 'New Event Registration' // Email subject
		),
	'newregistration' => array(
		'i' => true, // User invited someone else
		'f' => null, // no function
		'l' => 'event', // link to myunit to handle this
		't' => '{w} registered for {s} of {e}. ', // message text, first and last names
		'y' => 'Events', // confirm button
		'sy' => 'Events', // short confirm button
		'n' => null, // reject/no button
		's' => 'New Registration' // Email subject
		),
	'requestaccess' => array(
		'i' => true, // User invited someone else
		'f' => null, // no function
		'l' => 'unit', // link to myunit to handle this
		't' => '{f} {l} would like to be the alternate contact for {u}. ', // message text, first and last names
		'y' => 'Manage Unit Contacts', // confirm button
		'sy' => 'Contacts', // short confirm button
		'n' => null, // reject/no button
		's' => 'Contact Change Request' // Email subject
		),
	'paymentapproved' => array(
		'i' => true, // Payment was approved
		'f' => null, // no function
		'l' => 'payments', // link to myunit to handle this
		't' => 'Your ${a} payment for {e} has been confirmed. ', // a=amount, e=event
		'y' => 'Payments', // confirm button
		'sy' => 'Payments', // short confirm button
		'n' => null, // reject/no button
		's' => 'Payment Approved' // Email subject
		),
	'paymentcancelled' => array(
		'i' => true, // Payment was cancelled
		'f' => null, // no function
		'l' => 'payments', // link to myunit to handle this
		't' => 'Your ${a} payment for {e} has been cancelled.', // a=amount, e=event
		'y' => 'Payments', // confirm button
		'sy' => 'Payments', // short confirm button
		'n' => null, // reject/no button
		's' => 'Payment Cancelled' // Email subject
		),
	'paymentdeleted' => array(
		'i' => true, // Payment was cancelled
		'f' => null, // no function
		'l' => 'payments', // link to myunit to handle this
		't' => 'Your ${a} payment for {e} has been deleted.', // a=amount, e=event
		'y' => 'Payments', // confirm button
		'sy' => 'Payments', // short confirm button
		'n' => null, // reject/no button
		's' => null // Email subject
		),
	'paymentupdated' => array(
		'i' => true, // Payment was updated
		'f' => null, // no function
		'l' => 'payments', // link to myunit to handle this
		't' => 'One of your {t} payments for {e} has been modified.', // t=type, e=event
		'y' => 'Payments', // confirm button
		'sy' => 'Payments', // short confirm button
		'n' => null, // reject/no button
		's' => 'Payment Changed' // Email subject
		),
	'paymentpending' => array(
		'i' => true, // Payment pending admin review
		'f' => null, // no function
		'l' => 'payments', // link to myunit to handle this
		't' => '{u}\'s {t} payment for ${a} needs approval.', // a=amount, t=event
		'y' => 'Payments', // confirm button
		'sy' => 'Payments', // short confirm button
		'n' => null, // reject/no button
		's' => 'Payment Pending' // Email subject
		),
	'paymentpaypal' => array(
		'i' => true, // Successful paypal notification
		'f' => null, // no function
		'l' => 'payments', // link to myunit to handle this
		't' => '{u} completed a {t} payment for ${a}.', // a=amount, t=event
		'y' => 'Payments', // confirm button
		'sy' => 'Payments', // short confirm button
		'n' => null, // reject/no button
		's' => 'Online Payment Successful' // Email subject
		),
	'welcome' => array(
		'i' => true, // Welcome notification
		'f' => null, // no function
		'l' => null, // link to myunit to handle this
		't' => 'Hi {f}, welcome to '.$config['camper_systemname'].'!', // message text, first and last names
		'y' => null, // confirm button
		'sy' => null, // short confirm button
		'n' => null, // reject/no button
		's' => null // Email subject
		)
);

/* Static Lists
 *
 * These lists are static data sets that are used in common places such as forms. These include ranks, states, etc. 
 *
 * Since 1.0
 */

$config['camper_states'] = array(
	'INT'=>'International',
	'AL'=>'Alabama',
	'AK'=>'Alaska',
	'AZ'=>'Arizona',
	'AR'=>'Arkansas',
	'CA'=>'California',
	'CO'=>'Colorado',
	'CT'=>'Connecticut',
	'DE'=>'Delaware',
	'DC'=>'District of Columbia',
	'FL'=>'Florida',
	'GA'=>'Georgia',
	'HI'=>'Hawaii',
	'ID'=>'Idaho',
	'IL'=>'Illinois',
	'IN'=>'Indiana',
	'IA'=>'Iowa',
	'KS'=>'Kansas',
	'KY'=>'Kentucky',
	'LA'=>'Louisiana',
	'ME'=>'Maine',
	'MD'=>'Maryland',
	'MA'=>'Massachusetts',
	'MI'=>'Michigan',
	'MN'=>'Minnesota',
	'MS'=>'Mississippi',
	'MO'=>'Missouri',
	'MT'=>'Montana',
	'NE'=>'Nebraska',
	'NV'=>'Nevada',
	'NH'=>'New Hampshire',
	'NJ'=>'New Jersey',
	'NM'=>'New Mexico',
	'NY'=>'New York',
	'NC'=>'North Carolina',
	'ND'=>'North Dakota',
	'OH'=>'Ohio',
	'OK'=>'Oklahoma',
	'OR'=>'Oregon',
	'PA'=>'Pennsylvania',
	'RI'=>'Rhode Island',
	'SC'=>'South Carolina',
	'SD'=>'South Dakota',
	'TN'=>'Tennessee',
	'TX'=>'Texas',
	'UT'=>'Utah',
	'VT'=>'Vermont',
	'VA'=>'Virginia',
	'WA'=>'Washington',
	'WV'=>'West Virginia',
	'WI'=>'Wisconsin',
	'WY'=>'Wyoming',
	''=>'None'
);
